# Sponsor ApiBridge Pro
# These are supported funding model platforms

github: lukaslondono77
# patreon: yourusername
# open_collective: apibridge
# ko_fi: yourusername
# custom: ["https://buymeacoffee.com/yourusername"]

