# .github/FUNDING.yml

# Supported funding platforms:
# - github
# - patreon
# - open_collective
# - ko_fi
# - custom (for BuyMeACoffee, PayPal, etc.)

github: lukaslondono77       # enable when GitHub Sponsors is set up
patreon: yourusername        # optional
open_collective: apibridge   # optional
ko_fi: yourusername          # optional
custom: ["https://github.com/lukaslondono77"]
