# .github/FUNDING.yml

# Supported funding platforms:
# - github
# - patreon
# - open_collective
# - ko_fi
# - custom (for BuyMeACoffee, PayPal, etc.)

github: lukaslondono77       # enable when GitHub Sponsors is set up


